name: sending mail
on: push

jobs: 
  sendingmail:
    runs-on: windows-latest
    steps:
      - name: sending mail to mail id
        uses: devellany/send-mailer@v1.0.2
        with:
        host: smtp.google.com
        # Optional port (defaults to 465)
        port: 465
        account: ${{secrets.EMAIL_USERNAME}}
        password: ${{secrets.EMAIL_PASSWORD}}
        sender: devellany
        from: ${{secrets.MAIL_ADDRESS}}
        to: mailtoprakashdon@gmail.com
        subject: mail title.
        body: your messages.
        # Optional content type (defaults to text/plain)
        contentType: text/plain
        # Optional attachment files (JSON type. require property 'path')
        attachments: '[{"path":"README.md"}]'
    