name: sending mail
on: push

jobs:
  sendingmail:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Sending mail to mail ID
        uses: devellany/send-mailer@v1.0.2
        with:
          host: smtp.gmail.com
          port: 465
          account: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          sender: devellany
          from: ${{ secrets.MAIL_ADDRESS }}
          to: mailtoprakashdon@gmail.com
          subject: mail title.
          body: your messages.
          contentType: text/plain
          attachments: '[{"path":"README.md"}]'
