name: cronjob
on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:  
jobs:
  cronjob:
    runs-on: windows-latest
    steps:
    - name: clone Repo
      uses: actions/checkout@v3

    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: run
      run: python hi.py  
