name: run python
on: push

jobs:
  hello:
    runs-on: windows-latest

    steps:
      - name: clone repo
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: run python hello world
        run: python hello.py 
